// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetProjekt.Models;

namespace dotnetProjekt.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("dotnetProjekt.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rating")
                        .HasColumnType("float");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("dotnetProjekt.Models.Product+Images", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("dotnetProjekt.Models.Product+Keywords", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("keyword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("dotnetProjekt.Models.Product+Images", b =>
                {
                    b.HasOne("dotnetProjekt.Models.Product", null)
                        .WithMany("images")
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("dotnetProjekt.Models.Product+Keywords", b =>
                {
                    b.HasOne("dotnetProjekt.Models.Product", null)
                        .WithMany("keywords")
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("dotnetProjekt.Models.Product", b =>
                {
                    b.Navigation("images");

                    b.Navigation("keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
